
export enum MessageActionTypes {
  ADD_MESSAGE = '@@MESSAGE/ADD_MESSAGE',
  RESET_MESSAGE_LIST = '@@MESSAGE/RESET_MESSAGE_LIST',
  ADD_MESSAGE_LIST = '@@MESSAGE/ADD_MESSAGE_LIST',
  SET_SEEN_AT = '@@MESSAGE/SET_SEEN_AT',
}
